### ISSUE TITLE
Cannot port-forward because "socat" is not installed

### ISSUE THREAD

**Issue by sputnick** [TheNewNormal/kube-cluster-osx#100]
I read here https://github.com/coreos/bugs/issues/1114 that CoreOS won't ship with "socat" that is needed for "kubectl port-forward" although it was included in the CoreOS beta release. This makes local testing a bit hard for apps like the new Kubernetes Helm/Tiller (client/server). Since docker is being used and not Rkt doesn't it make sense to ship kube-cluster with socat? And is there any workaround?

**Comment by rimusz** [comment]
@sputnick yes, i'm going to include it soon. did that for kube-solo already.

**Comment by rimusz** [comment]
v0.5.1 got it

**Comment by jeffmhastings** [comment]
I have v0.5.3 and I'm getting this error

```
E0216 13:51:23.820517   86510 portforward.go:329] an error occurred forwarding 53825 -> 44134: error forwarding port 44134 to pod tiller-deploy-2779452559-ltgrj_kube-system, uid : unable to do port forwarding: socat not found.
Error: transport is closing
```

what is the workaround?

**Comment by jeffmhastings** [comment]
This is working after switching to the CoreOS Beta Release Channel. It would still be nice to know if there is a workaround for the Stable Release channel, or if there could have been some other issue.

**Comment by rimusz** [comment]
need to find a time to check out the stable version.

**Comment by finchr** [comment]
I'm also seeing this problem in v0.5.3 and the work around of switching to the CoreOS Beta Release Channel did not fix it for me.
