### ISSUE TITLE
Included binaries segfault on macOS Sierra

### ISSUE THREAD

**Issue by annismckenzie** [TheNewNormal/kube-cluster-osx#102]
I updated to macOS Sierra yesterday (in hindsight, I should've waited) and just fixed all of the included binaries to run correctly on Sierra. After a few hours wrestling with k8s the cluster is now up on macOS Sierra and Go 1.7.1 (compiled from source).

To make someone else's life easier I could fork the repo and provide the updated binaries if you want. The included `fleetctl`, `etcdctl` as well as `kubectl` need to be recompiled. Also, I noticed that `fleetctl` is included twice in the app, is that intended? Found the binaries in `/Applications/Kube-Cluster.app/Contents/Resources/bin/` as well as the additional `fleetctl` in `/Applications/Kube-Cluster.app/Contents/Resources/files/`.

Please advice – thanks for your hard work!

**Comment by annismckenzie** [comment]
To elaborate on why they segfault: it seems that almost all binaries compiled on pre-Sierra segfault or panic. If you're reading this and you haven't upgraded to Sierra, then please don't (at least not yet).

**Comment by AntonioMeireles** [comment]
@annismckenzie thanxs for reporting and for your patience. issue is infortunate and not specific to our tools (vd https://medium.com/@gerred/kubectl-1-3-7-for-macos-sierra-ee2c483e283d#.ajr1i0mx4) . we're working in getting it solved asap. just be aware that @rimusz is on travel so forgive us for a bit more latency than usual.

**Comment by cgswong** [comment]
Thanks for the heads up. Updated a while back and found out this issue myself. Will be waiting on the updated stack.

**Comment by rimusz** [comment]
fixed in #105
