### ISSUE TITLE
dyld: Library not loaded: /usr/local/opt/libev/lib/libev.4.dylib

### ISSUE THREAD

**Issue by mikelnrd** [TheNewNormal/kube-cluster-osx#109]
Hi I have corectl and kube-cluster installed (and iTerm). When I hit 'up' fro the kube-cluster menu I get the following. Any help to get this working would be appreciated thanks.

Kube-Cluster data disks do not exist, they will be created now ...

Creating 5GB sparse disk (QCow2) for Master ...
dyld: Library not loaded: /usr/local/opt/libev/lib/libev.4.dylib
  Referenced from: /Users/mike/bin/qcow-tool
  Reason: image not found
/Applications/Kube-Cluster.app/Contents/Resources/functions.sh: line 152: 15281 Abort trap: 6           ~/bin/qcow-tool create --size=5GiB master-data.img
-
Created 5GB Data disk for Master

Please type Nodes Data disk size in GBs followed by [ENTER]:
[default is 15]:

**Comment by mikelnrd** [comment]
If I type in a GB size (e.g. 16) I get...

Please type Nodes Data disk size in GBs followed by [ENTER]:
[default is 15]: 16

Creating 16GB sparse disk (QCow2) for Node1...
dyld: Library not loaded: /usr/local/opt/libev/lib/libev.4.dylib
  Referenced from: /Users/mike/bin/qcow-tool
  Reason: image not found
/Applications/Kube-Cluster.app/Contents/Resources/functions.sh: line 152: 16092 Abort trap: 6           ~/bin/qcow-tool create --size="$disk_size"GiB node-01-data.img
-
Created 16GB Data disk for Node1

Creating 16GB sparse disk (QCow2) for Node2...
dyld: Library not loaded: /usr/local/opt/libev/lib/libev.4.dylib
  Referenced from: /Users/mike/bin/qcow-tool
  Reason: image not found
/Applications/Kube-Cluster.app/Contents/Resources/functions.sh: line 152: 16094 Abort trap: 6           ~/bin/qcow-tool create --size="$disk_size"GiB node-02-data.img
-
Created 16GB Data disk for Node2

Starting k8smaster-01 VM ...
> booting k8smaster-01 (1/1)
[ERROR] stat master-data.img: no such file or directory

Master VM has not booted, please check '~/kube-cluster/logs/master_vm_up.log' and report the problem !!!

**Comment by mikelnrd** [comment]
And the log is just...

MacBook-Pro:~ mike$ cat ~/kube-cluster/logs/master_vm_up.log
> booting k8smaster-01 (1/1)
[ERROR] stat master-data.img: no such file or directory

**Comment by rimusz** [comment]
yes, you got cut by this issue https://github.com/TheNewNormal/kube-solo-osx/issues/156
till we sort it out you need to run : brew install libdev

**Comment by sputnick** [comment]
Small typo there @rimusz "libev" not "libdev" just FYI.

**Comment by mikelnrd** [comment]
Thanks! Happy to close the issue for now I'll open another one if that doesn't work.
