### ISSUE TITLE
access private docker registery

### ISSUE THREAD

**Issue by cobrowserAlex** [TheNewNormal/kube-cluster-osx#12]
I would like to use a private registry that I have running in a docker-machine exposed to my local.
What is the proper way to expose the host on the nodes?
I cannot reach by the ip mentioned at login or the docker-machine ip.

```
Last login: Fri Jan 29 15:50:33 on ttys002
 $ /Applications/Kube-Cluster.app/Contents/Resources/ssh_node1.command; exit;
Last login: Fri Jan 29 14:48:25 2016 from 192.168.64.1
CoreOS stable (835.11.0)
Update Strategy: No Reboots
 $ curl http://192.168.64.1:5000/v2
curl: (7) Failed to connect to 192.168.64.1 port 5000: Connection refused
 $ curl http://192.168.99.100/:5000/v2
```

**Comment by rimusz** [comment]
I do not use `docker-machine` (installs way too much things around I do not need) cannot comment on that matter.
Try my other App https://github.com/TheNewNormal/coreos-osx which has the Docker registry and you can build docker images there, and registry works on `192.168.64.1:5000` which is the bridge network

**Comment by cobrowserAlex** [comment]
Thanks @rimusz! Do you have any instructions on moving some big files of the kube-cluster or coreos-osx to another disk? My osx boot disk is almost full with all these images.
In the case of docker-machine i moved the disk.vmdk to another disk.

**Comment by cobrowserAlex** [comment]
Moved my question to https://github.com/TheNewNormal/coreos-osx/issues/29
