### ISSUE TITLE
Instsall and missing kubeconfig file

### ISSUE THREAD

**Issue by technosophos** [TheNewNormal/kube-cluster-osx#14]
During my first start up, a console window opened and the install seemed to be proceeding fine. ATHen I received a never-ending stream of these error messages:

```
rectory
\error: stat /Users/mattbutcher/kube-cluster/kube/kubeconfig: no such file or directory
|error: stat /Users/mattbutcher/kube-cluster/kube/kubeconfig: no such file or directory
/error: stat /Users/mattbutcher/kube-cluster/kube/kubeconfig: no such file or directory
-error: stat /Users/mattbutcher/kube-cluster/kube/kubeconfig: no such file or directory
\error: stat /Users/mattbutcher/kube-cluster/kube/kubeconfig: no such file or directory
|error: stat /Users/mattbutcher/kube-cluster/kube/kubeconfig: no such file or directory
/error: stat /Users/mattbutcher/kube-cluster/kube/kubeconfig: no such file or directory
-error: stat /Users/mattbutch
```

I seem to be stuck now.

**Comment by rimusz** [comment]
sure, will check the install script what's up there

**Comment by technosophos** [comment]
I got a shell opened, and here's what I see:

```
bash-3.2$ kubectl get no
error: stat /Users/mattbutcher/kube-cluster/kube/kubeconfig: no such file or directory
bash-3.2$ ls /Users/mattbutcher/kube-cluster/
bin         kubernetes      node-02-data.img
cloud-init      logs            settings
fleet           master-data.img     tmp
kube            node-01-data.img
bash-3.2$ ls /Users/mattbutcher/kube-cluster/kube
kube.tgz    kubectl
bash-3.2$
```

**Comment by rimusz** [comment]
can you try to delete the whole kube-cluster folder, of course do Halt via menu first.
and try to run setup again.
tomorrow I will look what can be causing the problem to generate the kubeconfig file

**Comment by technosophos** [comment]
That seems to have fixed it. And it looks like the problem is that I skipped a step while setting up. I'll close this.

**Comment by rimusz** [comment]
hmm, what kind of step did you skip, just to make sure anybody else cannot do it.

**Comment by technosophos** [comment]
I made a few, but the main one was that I didn't have the rsa key setup. I clicked through the prompt. I also think I might have run it the first time out of the dmg before dragging it to my apps folder. THat probably screwed up the environment.

**Comment by rimusz** [comment]
right I see, I think I'm going just include ssh keys in to package and use them.
and I will add Applications shortcut to the dmg, to be make easy to drag the App there
