### ISSUE TITLE
First run setup failed "open alpha: no such file or directory"

### ISSUE THREAD

**Issue by davidmankin** [TheNewNormal/kube-cluster-osx#23]
(Version 0.1.9; installed via `brew cask install kube-cluster`)

```
Creating 6GB Data disk for Node2 (it could take a while for big disks)...
   6GiB 0:00:09 [ 640MiB/s] [==================================>] 100%
Created 6GB Data disk for Node2

Starting k8smaster-01 VM ...
> booting k8smaster-01
Error: open alpha: no such file or directory

Usage:
  corectl load path/to/yourProfile [flags]

Examples:
  corectl load profiles/demo.toml

Global Flags:
      --debug   adds extra verbosity, and options, for debugging purposes and/or power users

All flags can also be configured via upper-case environment variables prefixed with "COREOS_"
For example, "--debug" => "COREOS_DEBUG"


Master VM has not booted, please check '~/kube-cluster/logs/master_vm_up.log' and report the problem !!!
```

**Comment by rimusz** [comment]
I have nothing to do with the brew cask at all, but if you check under https://github.com/TheNewNormal/kube-cluster-osx/releases you will see the note there:

```
It does not work with the latest CoreOS alpha 955/960/962 versions, please use beta/stable channels
```

The issue is already opened for that at https://github.com/TheNewNormal/corectl/issues/62

Please try the latest version from the github

**Comment by davidmankin** [comment]
Thanks for the reply; I did choose stable channel. I'm not sure whether it was 0.1.9 that was broken or the homebrew cask installation that broke it.  Anyway now that I see it's not even the latest release I think we can close this issue. Sorry for the noise.

**Comment by rimusz** [comment]
sure, no worries

**Comment by deinspanjer** [comment]
I hit this same problem on my first attempt at installing.  I had not rebooted and remembered that I had previously run docker-machine, so I figured it might have been the problem that was mentioned about virtualbox messing up stuff.  I rm'ed the kube-cluster directory and tried again and got further.
