### ISSUE TITLE
Fleet cannot find ETCD due to blank IP

### ISSUE THREAD

**Issue by shshang** [TheNewNormal/kube-cluster-osx#27]
Hi, 

I tried to install KUBE-cluster-osx multiple times. Every time, I ran into the same problem. 

All three nodes were launched, with IP equal to 182.168.64.2/3/4 respectively. I could see the process in the terminal and I could ping the IP without any problem.

[corectl] started 'k8smaster-01' in background with IP 192.168.64.2 and PID 7565
[corectl] started 'k8snode-01' in background with IP 192.168.64.3 and PID 7637
[corectl] started 'k8snode-02' in background with IP 192.168.64.4 and PID 7661

However, when fleetctl tried to talk to ECTD process (I believe in the k8smaster-01 node), for unknown reason, the IP in "dial" field is blank. Then the installation just hang afterwards.

fleetctl list-machines:
2016/03/22 23:27:19 ERROR fleetctl.go:216: error attempting to check latest fleet version in Registry: dial tcp :2379: connection refused
Error retrieving list of active machines: dial tcp :2379: connection refused

Starting all fleet units in ~/kube-cluster/fleet:
2016/03/22 23:27:19 ERROR fleetctl.go:216: error attempting to check latest fleet version in Registry: dial tcp :2379: connection refused
Error creating units: error retrieving Unit(fleet-ui.service) from Registry: dial tcp :2379: connection refused
2016/03/22 23:27:19 ERROR fleetctl.go:216: error attempting to check latest fleet version in Registry: dial tcp :2379: connection refused
Error creating units: error retrieving Unit(kube-apiserver.service) from Registry: dial tcp :2379: connection refused
2016/03/22 23:27:19 ERROR fleetctl.go:216: error attempting to check latest fleet version in Registry: dial tcp :2379: connection refused
Error creating units: error retrieving Unit(kube-controller-manager.service) from Registry: dial tcp :2379: connection refused
2016/03/22 23:27:19 ERROR fleetctl.go:216: error attempting to check latest fleet version in Registry: dial tcp :2379: connection refused
Error creating units: error retrieving Unit(kube-scheduler.service) from Registry: dial tcp :2379: connection refused
2016/03/22 23:27:19 ERROR fleetctl.go:216: error attempting to check latest fleet version in Registry: dial tcp :2379: connection refused
Error creating units: error retrieving Unit(kube-apiproxy.service) from Registry: dial tcp :2379: connection refused
2016/03/22 23:27:19 ERROR fleetctl.go:216: error attempting to check latest fleet version in Registry: dial tcp :2379: connection refused
Error creating units: error retrieving Unit(kube-kubelet.service) from Registry: dial tcp :2379: connection refused
2016/03/22 23:27:19 ERROR fleetctl.go:216: error attempting to check latest fleet version in Registry: dial tcp :2379: connection refused
Error creating units: error retrieving Unit(kube-proxy.service) from Registry: dial tcp :2379: connection refused

Waiting for Kubernetes cluster to be ready. This can take a few minutes...

I tried both "stable" and "beta" release. The result is the same.

How can I perform further troubleshooting?

Thanks!

Shixiong

**Comment by rimusz** [comment]
hmm that's the weird one, need to look what could cause that

**Comment by vishalmodak** [comment]
I am running in to the same issue. tried several times...but no luck.

**Comment by rimusz** [comment]
@vishalmodak had run virtual box? if yes try to reboot.
Also can you try the kube-solo one app, and see if you get the same issue.
thanks

**Comment by vishalmodak** [comment]
tried the reboot...same issue...another issue is that..the master & nodes are up ...I get an error 
'k8smaster-01' not found or dead

```
Starting k8smaster-01 VM ...
> booting k8smaster-01
[corectl] stable/899.17.0 already available on your system
[corectl] '/Users/1337135' was already available to VMs via NFS
[corectl] started 'k8smaster-01' in background with IP 192.168.64.2 and PID 1316
Error: 'k8smaster-01' not found, or dead

Usage:
  corectl query [VMids] [flags]

Aliases:
  query, q

Flags:
  -a, --all    display extended information about a running CoreOS instance
  -i, --ip     displays given instance IP address
  -j, --json   outputs in JSON for easy 3rd party integration

Global Flags:
      --debug   adds extra verbosity, and options, for debugging purposes and/or power users

All flags can also be configured via upper-case environment variables prefixed with "COREOS_"
For example, "--debug" => "COREOS_DEBUG"

Error: 'k8smaster-01' not found, or dead

Usage:
  corectl query [VMids] [flags]

Aliases:
  query, q

Flags:
  -a, --all    display extended information about a running CoreOS instance
  -i, --ip     displays given instance IP address
  -j, --json   outputs in JSON for easy 3rd party integration

Global Flags:
      --debug   adds extra verbosity, and options, for debugging purposes and/or power users

All flags can also be configured via upper-case environment variables prefixed with "COREOS_"
For example, "--debug" => "COREOS_DEBUG"
```

**Comment by vishalmodak** [comment]
@rimusz ..tried to kube-solo app...same issue...

```
fleetctl list-machines:
2016/05/17 13:27:12 ERROR fleetctl.go:216: error attempting to check latest fleet version in Registry: dial tcp :2379: getsockopt: connection refused
Error retrieving list of active machines: dial tcp :2379: getsockopt: connection refused

Starting all fleet units in ~/kube-solo/fleet:
2016/05/17 13:27:12 ERROR fleetctl.go:216: error attempting to check latest fleet version in Registry: dial tcp :2379: getsockopt: connection refused
Error creating units: error retrieving Unit(fleet-ui.service) from Registry: dial tcp :2379: getsockopt: connection refused
2016/05/17 13:27:12 ERROR fleetctl.go:216: error attempting to check latest fleet version in Registry: dial tcp :2379: getsockopt: connection refused
Error creating units: error retrieving Unit(kube-apiserver.service) from Registry: dial tcp :2379: getsockopt: connection refused
2016/05/17 13:27:12 ERROR fleetctl.go:216: error attempting to check latest fleet version in Registry: dial tcp :2379: getsockopt: connection refused
Error creating units: error retrieving Unit(kube-controller-manager.service) from Registry: dial tcp :2379: getsockopt: connection refused
2016/05/17 13:27:12 ERROR fleetctl.go:216: error attempting to check latest fleet version in Registry: dial tcp :2379: getsockopt: connection refused
Error creating units: error retrieving Unit(kube-scheduler.service) from Registry: dial tcp :2379: getsockopt: connection refused
2016/05/17 13:27:12 ERROR fleetctl.go:216: error attempting to check latest fleet version in Registry: dial tcp :2379: getsockopt: connection refused
Error creating units: error retrieving Unit(kube-kubelet.service) from Registry: dial tcp :2379: getsockopt: connection refused
2016/05/17 13:27:12 ERROR fleetctl.go:216: error attempting to check latest fleet version in Registry: dial tcp :2379: getsockopt: connection refused
Error creating units: error retrieving Unit(kube-proxy.service) from Registry: dial tcp :2379: getsockopt: connection refused

fleetctl list-units:
2016/05/17 13:27:12 ERROR fleetctl.go:216: error attempting to check latest fleet version in Registry: dial tcp :2379: getsockopt: connection refused
Error retrieving list of units from repository: dial tcp :2379: getsockopt: connection refused

Generate kubeconfig file ...
cluster "k8solo-01" set.
context "default-context" set.
switched to context "default-context".
Waiting for Kubernetes cluster to be ready. This can take a few minutes...
```

hung up at this point...

**Comment by rimusz** [comment]
@vishalmodak right it could be docker is not starting on the VM.
Can you check the internet is accessible from the VM? as flannel docker image needs to be download which later used to start flannel and docker depends on it.

**Comment by rimusz** [comment]
@shshang can you check the ^^ too, please. 
thanks

**Comment by rimusz** [comment]
the check for etcd functionality is in place, the error message should inform if etcd is not working
