### ISSUE TITLE
kube-cluster-osx/src/bin/fleetctl  SEEMS TO BE AN OLD VERSION

### ISSUE THREAD

**Issue by zhangwei** [TheNewNormal/kube-cluster-osx#34]
Hi

Are you going to update fleetctl to the new version?
kube-cluster-osx/src/bin/fleetctl is 0.11.5.
the latest version is fleet v0.11.7.

Thanks.

**Comment by rimusz** [comment]
@zhangwei I'm going to update it in a few days

**Comment by rimusz** [comment]
fixed in v0.2.4
