### ISSUE TITLE
Monochromatic Status Bar Icon

### ISSUE THREAD

**Issue by tynor** [TheNewNormal/kube-cluster-osx#42]
I don't have the skills to actually pull this off, but I would really appreciate an option for a black/transparent status bar icon. My entire menu bar is this style except for the Kube-Cluster icon and it's fairly jarring:
<img width="804" alt="screen shot 2016-06-03 at 9 58 10 pm" src="https://cloud.githubusercontent.com/assets/1875173/15797735/c9c07b44-29d6-11e6-853a-f748b7827ec4.png">

**Comment by rimusz** [comment]
@tynor I do not have much skills in that too, but will try to look to it at some point

**Comment by rimusz** [comment]
fix by @ipedrazas is merged to master, on the next release it will be added
