### ISSUE TITLE
Error: "VM's are OFF !!!"

### ISSUE THREAD

**Issue by remoe** [TheNewNormal/kube-cluster-osx#53]
I've tried the latest version on a Mac 10.10.5 (@0.2.9). The VM's are always OFF. It doesn't start any VM's. Does anyone know where I can find the logs about it?

Thanks

**Comment by rimusz** [comment]
@remoe that's very weird one, 
@AntonioMeireles (ping) some advice?

**Comment by AntonioMeireles** [comment]
@remoe 

Hi! to start - behind some sort of firewall ?
also, you seem to be in a similar timezone as i am (just one hour ahead). would you tomorrow be available for a joint debug sprint ?

**Comment by remoe** [comment]
@AntonioMeireles , yes I have a firewall behind. Does it use others then 80 or 443? I don't have used kube-cluster-osx before. It's my first time :)

**Comment by AntonioMeireles** [comment]
@remoe will ping you tomorrow morning to hep you debug this :-) && thanks for your patience!

**Comment by remoe** [comment]
@AntonioMeireles ok.

**Comment by remoe** [comment]
@AntonioMeireles, sorry, please ping me in the evening.

**Comment by remoe** [comment]
@AntonioMeireles ping :)

**Comment by AntonioMeireles** [comment]
@remoe can you PM me in kubernetes' slack ?

**Comment by remoe** [comment]
@AntonioMeireles @rimusz thanks for your support! It was my old iTerm v1.0 (https://iterm2.com/). I've updated to 2.1.4 and it works now! ;)

**Comment by Hashfyre** [comment]
I'm experiencing this with iterm Build 3.0.5. 
KubeCluster version is v0.2.7.

I'll update this comment once I move to v0.4.8 latest
