### ISSUE TITLE
Install Deis script waiting for the wrong node

### ISSUE THREAD

**Issue by MaxenceAdnot** [TheNewNormal/kube-cluster-osx#6]
Hi,

Thank you for your great work. I tried installing deis v2 alpha with "install_deis" and I got the message : "Waiting for Deis PaaS to be ready... but first, coffee!"

It seems that in my case the node1 IP is 192.168.64.3 but Deis workflow is running at 192.168.64.4 and "deis register http://deis.192.168.64.4.xip.io" reach correctly the controller.

The install_deis should be modified to wait for workflow on one of the two nodes, not only the first one.

**Comment by rimusz** [comment]
I need to adjust the `install_deis` script to pick automatically the router node, as via router you need to connect to workflow.

**Comment by rimusz** [comment]
released v0.1.5 where Deis router gets pinned to node1

**Comment by deinspanjer** [comment]
I'm trying to run install_deis, but it is hanging at the same place.  This is with the latest version downloaded and installed today, 2.8
