### ISSUE TITLE
Registry credentials

### ISSUE THREAD

**Issue by cobrowserAlex** [TheNewNormal/kube-cluster-osx#60]
We are using a private registry and with your help we are now able to access it, but it requires credentials.
These credentials are normally put in `/var/lib/kubelet/.dockercfg` and putting them there works fine. 
However they are removed after e halt or reload.

Is there anyway to run a script on startup to put them there from a shared directory, or use cloudinit?

**Comment by rimusz** [comment]
nfs will be an optional soon (too much problems with it), so shared folder is not an option.

cloud-init will work fine, but if you update the App, you need to update the cloud-init file again.

I can add an extra mount for `/var/lib/kubelet` to make it persistent folder

**Comment by rimusz** [comment]
@cobrowserAlex here we go v0.3.3 will persist `/var/lib/kubelet` folder

**Comment by cobrowserAlex** [comment]
Great, thanks @rimusz

**Comment by cobrowserAlex** [comment]
@rimusz i especially like the 

```
Checking internet availablity on master VM...
Yes, internet is available ...
```

**Comment by rimusz** [comment]
cool
