### ISSUE TITLE
Kubernetes tar file and AddOn services are out of date.

### ISSUE THREAD

**Issue by Krylon360** [TheNewNormal/kube-cluster-osx#69]
The Initial Setup is deploying an outdated SkyDNS; as well as an outdated Kubernetes-Dashboard.
Even when running the "Update to latest Stable Kubernetes Version" option is used; it still re-deploys old services. It looks like you've staticly added in an old kube.tar and rc/svc yaml's.
It would be better to run the command: 
export KUBERNETES_PROVIDER=vagrant; curl -sS https://get.k8s.io | bash
vs using hard-coded files for setting up kubernetes.

**Comment by rimusz** [comment]
@Krylon360 which App version are you talking about?
the latest v0.4.0 comes with k8s v1.3 and latest SkyDNS and Kubernetes-Dashboard, whatever v1.3 had in github

Also if you can improve the update part, PRs are always welcome :)
btw hardcoded tars are by users requests :) afterwards  you can update to the latest or pick an available version from github

**Comment by Krylon360** [comment]
v0.3.5 (You hadn't merged in v0.4.0 yet; which looks like you just did.)
(speaking of which; how hard would it be to add a "Check for Update/Update Kube-Cluster for macOS" option? 👍  )

Here's the current services deployed.
![screen shot 2016-07-08 at 3 18 42 pm](https://cloud.githubusercontent.com/assets/320206/16701846/bcc946dc-451f-11e6-8d4f-dd9e06cfe59f.png)
When pulling down the source for the app and looking at the deployment files; here are the image:tags that are being pulled.
skydns-rc.yaml > 
name: kube-dns-v10
version: v10 
name: etcd
image: gcr.io/google_containers/etcd:2.0.9
name: kube2sky
image: gcr.io/google_containers/kube2sky:1.12
name: skydns
image: gcr.io/google_containers/skydns:2015-10-13-8c72f8c

dashboard-controller.yaml >
name: kubernetes-dashboard
image: gcr.io/google_containers/kubernetes-dashboard-amd64:v1.0.1

**Comment by Krylon360** [comment]
Same issue with 0.4.0.

kube-cluster-osx-0.4.0 cat src/k8s/skydns-rc.yaml |grep "version:"
    version: v10
    version: v10
        version: v10

**Comment by rimusz** [comment]
sure, must be missed the skydns so how, will update in the next version.
regarding App's upgrade, to add an option to check for the upgrade via menu and on App's start should not be too difficult. 
upgrading in place does not always work as can be many changes to fleet units/cloud-init/kubernetes that makes a difficult task. need to think about this one.

**Comment by rimusz** [comment]
@Krylon360 updated SkyDNS to v17, closing this one, as I have issues opened for Apps updates check #71 and Add-ons update check #70

**Comment by Krylon360** [comment]
Awesome. Thanks @Rimas

Bryce Walter
