### ISSUE TITLE
Cluster fails to read non-existing value on start

### ISSUE THREAD

**Issue by necrogami** [TheNewNormal/kube-cluster-osx#76]
OSX 10.11.5

Last login: Tue Jul 12 16:58:43 on ttys001

---

| ~ @ Antons-MBP-2 (necrogami)
| => /Applications/Kube-Cluster.app/Contents/Resources/up.command; exit;

Data disks do not exist, they will be created now ...

Creating 2GB Data disk for Master ...
   2GiB 0:00:01 [1.49GiB/s] [=======================================================================================>] 100%
Created 2GB Data disk for Master

Please type Nodes Data disk size in GBs followed by [ENTER]:
[default is 10]:

Creating 10GB Data disk for Node1...
  10GiB 0:00:06 [1.48GiB/s] [=======================================================================================>] 100%
Created 10GB Data disk for Node1

Creating 10GB Data disk for Node2...
  10GiB 0:00:06 [1.48GiB/s] [=======================================================================================>] 100%
Created 10GB Data disk for Node2

Starting k8smaster-01 VM ...
[WARN] unable to run "defaults read /Library/Preferences/SystemConfiguration/com.apple.vmnet.plist" Shared_Net_Address ...
[WARN] ... assuming macOS default value (192.168.64.1)
[WARN] unable to run "defaults read /Library/Preferences/SystemConfiguration/com.apple.vmnet.plist" Shared_Net_Mask ...
[WARN] ... assuming macOS default value (255.255.255.0)
[ERROR] exit status 1

Master VM has not booted, please check '~/kube-cluster/logs/master_vm_up.log' and report the problem !!!

Press [Enter] key to continue...

**Comment by rimusz** [comment]
this is `corectl` problem , I opened an issue at https://github.com/TheNewNormal/corectl/issues/83
and the old issue https://github.com/TheNewNormal/corectl/issues/80

**Comment by rimusz** [comment]
ok, issue is fixed with the latest `corectl` v0.7.9 to which you can update via `corectl.app` menu option `Check for corectld updates`
