### ISSUE TITLE
etcd never seems to start

### ISSUE THREAD

**Issue by necrogami** [TheNewNormal/kube-cluster-osx#79]
I've tried this multiple times now. via destroying and re-upping I get through creating the nodes but it hangs at waiting for etcd service to be ready

Last login: Wed Jul 13 10:34:46 on ttys007

---

| ~ @ aswartz (necrogami)
| => /Applications/Kube-Cluster.app/Contents/Resources/up.command; exit;

Data disks do not exist, they will be created now ...

Creating 2GB Data disk for Master ...
   2GiB 0:00:01 [1.45GiB/s] [================================>] 100%
Created 2GB Data disk for Master

Please type Nodes Data disk size in GBs followed by [ENTER]:
[default is 10]:

Creating 10GB Data disk for Node1...
  10GiB 0:00:06 [1.44GiB/s] [================================>] 100%
Created 10GB Data disk for Node1

Creating 10GB Data disk for Node2...
  10GiB 0:00:06 [1.45GiB/s] [================================>] 100%
Created 10GB Data disk for Node2

Starting k8smaster-01 VM ...

> booting k8smaster-01 (1/1)
> ---> 'k8smaster-01' started successfuly with address 192.168.64.2 and PID 35507
> ---> 'k8smaster-01' boot logs can be found at '/Users/necrogami/.coreos/running/7E79BC00-7E3C-4B19-9CDF-83F99FD73A23/log'
> ---> 'k8smaster-01' console can be found at '/Users/necrogami/.coreos/running/7E79BC00-7E3C-4B19-9CDF-83F99FD73A23/tty'

Starting k8snode-01 VM ...

> booting k8snode-01 (1/1)
> ---> 'k8snode-01' started successfuly with address 192.168.64.3 and PID 35680
> ---> 'k8snode-01' boot logs can be found at '/Users/necrogami/.coreos/running/31D7ADDF-96D7-428A-A17F-14CB902CCD05/log'
> ---> 'k8snode-01' console can be found at '/Users/necrogami/.coreos/running/31D7ADDF-96D7-428A-A17F-14CB902CCD05/tty'

Starting k8snode-02 VM ...

> booting k8snode-02 (1/1)
> ---> 'k8snode-02' started successfuly with address 192.168.64.4 and PID 35748
> ---> 'k8snode-02' boot logs can be found at '/Users/necrogami/.coreos/running/0ECA856A-ACE8-4EA2-A906-1B53BB071C69/log'
> ---> 'k8snode-02' console can be found at '/Users/necrogami/.coreos/running/0ECA856A-ACE8-4EA2-A906-1B53BB071C69/tty'

Waiting for etcd service to be ready on k8smaster-01 VM...

**Comment by necrogami** [comment]
I've waited over an hour with no results.

**Comment by rimusz** [comment]
@necrogami usually etcd comes very quick.
can you try to delete the whole `~/kube-cluster` folder first and run the app again?
Are you using the latest app version v0.4.3?

Or would you mind to check kube-solo app?
might be easier to found your problem.
Could be some networking issues on you Mac, firewall e.g.?

**Comment by necrogami** [comment]
Now after updating it's saying this: 

Checking internet availablity on VMs...
There is no internet access from the k8smaster-01 VM !!!
That also means could be the same issue on nodes as well.

Please check you Mac's firewall, network setup and fix the problem.

k8smaster-01 and node VMs are still running, so you can troubleshoot the network problem
and when you done just 'Halt' and 'Up' via menu and the installation will continue ...

Press [Enter] key to abort installation ...

I have internet access just updated to newest corectl app and kube-cluster app.

**Comment by necrogami** [comment]
It's a brand new mac under a week old. I deleted the kube-cluster before updating apps, everything is default for the most part i haven't messed with the firewall.

**Comment by AntonioMeireles** [comment]
@necrogami are you using a VPN of some sort ?

**Comment by necrogami** [comment]
No vpn, i haven't gotten around to setting up/installing my office vpn. I have dual network via USB Gbit ethernet and wifi.

**Comment by necrogami** [comment]
Via Solo app: 

Last login: Wed Jul 13 12:07:09 on ttys006

---

| ~ @ aswartz (necrogami)
| => /Applications/Kube-Solo.app/Contents/Resources/first-init.command; exit;

Setting up Kubernetes Solo Cluster on macOS

Reading ssh key from /Users/necrogami/.ssh/id_rsa.pub

/Users/necrogami/.ssh/id_rsa.pub found, updating configuration files ...

Set CoreOS Release Channel:
 1)  Alpha (may not always function properly)
 2)  Beta
 3)  Stable (recommended)

Select an option: 3

Please type VM's RAM size in GBs followed by [ENTER]:
[default is 2]:
Changing VM's RAM to 2GB...

Please type Data disk size in GBs followed by [ENTER]:
[default is 15]:

Creating 15GB disk ...
  15GiB 0:00:11 [1.29GiB/s] [================================>] 100%
Created 15GB Data disk

Starting VM ...

> booting k8solo-01 (1/1)
> ---> 'k8solo-01' started successfuly with address 192.168.64.5 and PID 97395
> ---> 'k8solo-01' boot logs can be found at '/Users/necrogami/.coreos/running/90394897-5956-4F9D-AFC4-E274C45DAB31/log'
> ---> 'k8solo-01' console can be found at '/Users/necrogami/.coreos/running/90394897-5956-4F9D-AFC4-E274C45DAB31/tty'

Generating kubeconfig file ...
cluster "k8solo-01" set.
context "kube-solo" set.
switched to context "kube-solo".

Checking internet availablity on VM...
There is no internet access from the VM !!!

Please check you Mac's firewall, network setup

k8solo-01 VM is still running, so you can troubleshoot the network problem
and when you done just 'Halt' and 'Up' via menu and the installation will continue ...

**Comment by AntonioMeireles** [comment]
`corectl ssh k8solo-01 "dig github.com"` returns what (from mac's cli)

**Comment by necrogami** [comment]
---

| ~ @ aswartz (necrogami) 
| => corectl ssh k8solo-01 "dig github.com"

; <<>> DiG 9.10.2-P4 <<>> github.com
;; global options: +cmd
;; connection timed out; no servers could be reached
[ERROR] Process exited with status 9

---

| ~ @ Antons-MacBook-Pro-2 (necrogami) 
| => dig github.com +short
192.30.253.113

**Comment by AntonioMeireles** [comment]
(on the mac) `dig @localhost github.com +short` also works ?

**Comment by necrogami** [comment]
---

| ~ @ aswartz (necrogami) 
| => dig @localhost github.com +short
192.30.253.112

**Comment by AntonioMeireles** [comment]
that's "interesting". (just for the sake of it) if you disable Mac's firewall things work (from within the VM), or still fail ?

**Comment by necrogami** [comment]
What do you mean?

**Comment by AntonioMeireles** [comment]
Apple Menu -> System Preferences -> Security & Privacy -> Turn Off Firewall

(just try - to find out if somehow is fwall related)

**Comment by necrogami** [comment]
It was already turned off. I went there and it was already off.

**Comment by AntonioMeireles** [comment]
weird. can you join kubernetes slack and ping me there - to try do debug this interactivelly ?

**Comment by necrogami** [comment]
what's the slack address?

**Comment by AntonioMeireles** [comment]
kubernetes.slack.com

**Comment by AntonioMeireles** [comment]
user had dnsmask running on his box which was messing up things. disabling it made things work as advertized :-)
