### ISSUE TITLE
Allow kube cluster/solo to work with existing dns

### ISSUE THREAD

**Issue by necrogami** [TheNewNormal/kube-cluster-osx#80]
I have dnsmasq running on my laptop for development purposes this conflicts with skydns also wanting to use port 53. I'd suggest 2 things 1 put in detection that will warn the user that something is running on port 53 and will conflict with skydns and 2 later develop a solution for cascading dns services.

**Comment by rimusz** [comment]
@necrogami detection is in the latest v0.4.5. Not sure about the cascading DNS solution.
closing this issue for nor
