### ISSUE TITLE
This file can’t be copied because there is a problem with the file.

### ISSUE THREAD

**Issue by mtsr** [TheNewNormal/kube-cluster-osx#85]
When I try to install the app by copying to /Applications I get this error:

`This file can’t be copied because there is a problem with the file.`

This is from a fresh download of 0.4.3 and 0.4.2. I've also tried building the app myself, but I get an Info.plist error.

**Comment by mtsr** [comment]
Solved after a reboot, for some reason.

**Comment by rimusz** [comment]
@mtsr it is nothing to do with the App, just reboot your Mac.
I see such problem time by time myself too

**Comment by mtsr** [comment]
Hi Rimas,

Thanks, that also solved the issue with building the app.

Cheers,

Jonas
