### ISSUE TITLE
Initial setup can't find /usr/local/sbin/qcow-tool

### ISSUE THREAD

**Issue by davecaplinger** [TheNewNormal/kube-cluster-osx#92]
(Now that I have corectl.app running...) Running initial setup fails when creating the vms.  Each disk fails with logs like:

```
Creating 5GB sparse disk (QCow2) for Master ...
/Applications/Kube-Cluster.app/Contents/Resources/functions.sh: line 160: /usr/local/sbin/qcow-tool: No such file or directory
-
Created 5GB Data disk for Master
```

Obviously, I don't have `/usr/local/sbin/qcow-tool` (I checked), but am not sure where it was supposed to come from.  It's not a part of corectl.app, CoreOS.app, Kube-Cluster.app, nor is it available via brew as a quick workaround.  Did I miss a prerequisite?

**Comment by rimusz** [comment]
@davecaplinger corectl.app suppose to copy all corectl relared files to that folder. try to restart the corectl.app as it checks if some files are missing it copies on the start

**Comment by rimusz** [comment]
those files usually get copied to `/usr/local/sbin/` folder if `correct.app` does not find them there:

```
/Applications/corectl.app/Contents/Resources/bin$ ls
corectl*         corectld*        corectld.runner* qcow-tool*
```

I'm interested to reproduce such issue

**Comment by rimusz** [comment]
this one should be solved with the latest `corectl.app` v0.2.3
